### ISSUE TITLE
Using Ability Scores, pg 76-83; Adventuring, pg 84-89; Combat, pg 90-99

### ISSUE THREAD

**Issue by amazingrando** [amazingrando/fifth-edition-srd#6]
> I thought I'd tackle "Playing the Game", but it seemed to be title "Using Ability Scores" in the SRD.  I guess we can sort that out once I'm ready for a pull request.

@jhoffmannrim I think that this is the section that you wanted to tackle. If not, let me know which one you'd like to have. Thanks!

**Comment by jhhoffmann** [comment]
You've assigned this issue to my work github account, `jhoffmannrim`.  I don't use that account anymore, especially since I don't work at that company anymore.  Please re-assign to my personal github account `jhhoffmann`.

**Comment by amazingrando** [comment]
@jhhoffmann Done!

**Comment by amazingrando** [comment]
Updated the issue to reflect the extra work that you're doing.
